import requests
import json
class OllamaModel:
    def __init__(self, model_name="llama3.2:3b"):
        self.model_name = model_name
        self.api_url = "http://localhost:11434/api/chat"  # Default Ollama API endpoint

    def generate_structured_data(self, text, section_name):
    # Define prompts based on the section name
        if section_name == "EDUCATION":
            prompt = (
                f"Extract the education details from the following CV section. "
                f"List all degrees, institutions, and dates:\n\n"
                f"Input:\n{text}\n\n"
                f"Output format:\n"
                f"Education:\n- Degree: [Degree Name], Institution: [Institution Name], Dates: [Start-End]\n"
            )
        elif section_name == "PROFESSIONAL EXPERIENCE":
            prompt = (
                f"Extract the professional experience details from the following CV section. "
                f"List all job titles, companies, and dates:\n\n"
                f"Input:\n{text}\n\n"
                f"Output format:\n"
                f"Experience:\n- Job Title: [Job Title], Company: [Company Name], Dates: [Start-End]\n"
            )
        elif section_name == "CERTIFICATES":
            prompt = (
                f"Extract the certificates from the following CV section. "
                f"List all certificates and their dates:\n\n"
                f"Input:\n{text}\n\n"
                f"Output format:\n"
                f"Certifications:\n- Certificate: [Certificate Name], Date: [Date]\n"
            )
        elif section_name == "SKILLS":
            prompt = (
                f"Extract the skills from the following CV section. "
                f"List all skills:\n\n"
                f"Input:\n{text}\n\n"
                f"Output format:\n"
                f"Skills:\n- [Skill 1]\n- [Skill 2]\n"
            )
        else:
            # Default case for unsupported sections
            prompt = (
                f"Analyze the following CV section and extract relevant information:\n\n"
                f"Input:\n{text}\n\n"
                f"Output format:\n"
                f"- [Extracted Information]\n"
            )

        # Send the prompt to the Ollama API
        response = requests.post(
            self.api_url,
            json={"model": self.model_name, "messages": [{"role": "user", "content": prompt}]},
            stream=True  # Enable streaming
        )

        if response.status_code == 200:
            try:
                # Collect the streamed response content
                content = ""
                for line in response.iter_lines():
                    if line:  # Skip empty lines
                        line_data = json.loads(line.decode("utf-8"))
                        message = line_data.get("message", {}).get("content", "")
                        content += message

                return content.strip()  # Return the full content
            except Exception as e:
                raise Exception(f"Failed to parse streaming response: {e}, Raw response: {response.text}")
        else:
            raise Exception(f"Error: {response.status_code}, {response.text}")
    
    def split_cv_into_sections(self, cv_text):
        sections = {}
        current_section = None
        for line in cv_text.splitlines():
            line = line.strip()
            if not line:
                continue
            if line.upper() in ["EDUCATION", "PROFESSIONAL EXPERIENCE", "CERTIFICATES", "SKILLS"]:
                current_section = line.upper()
                sections[current_section] = []
            elif current_section:
                sections[current_section].append(line)
        for section in sections:
            sections[section] = "\n".join(sections[section])
        return sections

    def process_cv(self, cv_text):
        """
        Process the entire CV text using the Ollama model.
        :param cv_text: The raw CV text.
        :return: The structured data generated by the model.
        """
        # Define the initial prompt for processing the CV
        prompt = (
            f"Analyze the following CV and extract structured information including Education, "
            f"Professional Experience, Certificates, and Skills. Provide the output in JSON format:\n\n"
            f"Input:\n{cv_text}\n\n"
            f"Output format:\n"
            f"{{\n"
            f"  \"EDUCATION\": [\n"
            f"    {{\"Degree\": \"\", \"Institution\": \"\", \"Dates\": \"\"}}\n"
            f"  ],\n"
            f"  \"PROFESSIONAL EXPERIENCE\": [\n"
            f"    {{\"Job Title\": \"\", \"Company\": \"\", \"Dates\": \"\"}}\n"
            f"  ],\n"
            f"  \"CERTIFICATES\": [\n"
            f"    {{\"Certificate\": \"\", \"Date\": \"\"}}\n"
            f"  ],\n"
            f"  \"SKILLS\": {{\n"
            f"    \"Web Development\": [\"\"],\n"
            f"    \"Programming Languages\": [\"\"],\n"
            f"    \"Other Skills\": [\"\"]\n"
            f"  }}\n"
            f"}}"
        )

        # Send the initial prompt to the Ollama API
        response = requests.post(
            self.api_url,
            json={"model": self.model_name, "messages": [{"role": "user", "content": prompt}]},
            stream=True  # Enable streaming
        )

        if response.status_code == 200:
            try:
                # Collect the streamed response content
                content = ""
                for line in response.iter_lines():
                    if line:  # Skip empty lines
                        line_data = json.loads(line.decode("utf-8"))
                        message = line_data.get("message", {}).get("content", "")
                        content += message

                # Resend the response to Ollama to extract only JSON
                clean_prompt = (
                    f"Extract only the JSON from the following response. "
                    f"Do not include any additional text, explanations, or characters. "
                    f"Your response must be valid JSON and nothing else:\n\n"
                    f"{content}"
                )
                clean_response = requests.post(
                    self.api_url,
                    json={"model": self.model_name, "messages": [{"role": "user", "content": clean_prompt}]},
                    stream=True  # Enable streaming
                )

                if clean_response.status_code == 200:
                    # Collect the streamed response content for the clean JSON
                    clean_content = ""
                    for line in clean_response.iter_lines():
                        if line:  # Skip empty lines
                            line_data = json.loads(line.decode("utf-8"))
                            message = line_data.get("message", {}).get("content", "")
                            clean_content += message

                    # Parse the clean JSON content
                    return json.loads(clean_content.strip())
                else:
                    raise Exception(f"Error in clean response: {clean_response.status_code}, {clean_response.text}")
            except Exception as e:
                raise Exception(f"Failed to parse streaming response: {e}, Raw response: {content}")
        else:
            raise Exception(f"Error: {response.status_code}, {response.text}")

    # CV Improvement Methods
    def improve_cv(self, cv_data):
        """
        Improve the CV by enhancing content and generating suggestions.
        :param cv_data: A dictionary containing structured CV data.
        :return: A dictionary with improved CV content and suggestions.
        """
        improved_cv = {}
        for section_name, section_text in cv_data.items():
            # Step 1: Correct grammar and spelling
            corrected_text = self.correct_grammar(section_text)

            # Step 2: Enhance vague descriptions
            enhanced_text = self.enhance_description(corrected_text)

            # Step 3: Add suggestions for improvement
            suggestions = self.generate_suggestions(section_name, enhanced_text)

            # Combine the improved content and suggestions
            improved_cv[section_name] = {
                "content": enhanced_text,
                "suggestions": suggestions
            }

        # Add a summary of overall improvements
        overall_suggestions = self.generate_overall_suggestions(improved_cv)
        improved_cv["summary"] = overall_suggestions

        return improved_cv


    def correct_grammar(self, text):
        """
        Correct grammar and spelling in the given text.
        :param text: The input text.
        :return: The corrected text.
        """
        # Use Ollama to correct grammar
        prompt = f"Correct the grammar and spelling in the following text:\n{text}"
        response = requests.post(
            self.api_url,
            json={"model": self.model_name, "messages": [{"role": "user", "content": prompt}]},
            stream=True  # Enable streaming
        )

        if response.status_code == 200:
            try:
                # Collect the streamed response content
                content = ""
                for line in response.iter_lines():
                    if line:  # Skip empty lines
                        line_data = json.loads(line.decode("utf-8"))
                        message = line_data.get("message", {}).get("content", "")
                        content += message

                return content.strip()  # Return the full content
            except Exception as e:
                raise Exception(f"Failed to parse streaming response: {e}, Raw response: {response.text}")
        else:
            raise Exception(f"Error: {response.status_code}, {response.text}")

    def enhance_description(self, text):
        """
        Enhance vague descriptions in the CV.
        :param text: The input text.
        :return: The enhanced text.
        """
        # Use Ollama to rewrite vague descriptions
        prompt = f"Improve the following CV description:\n{text}"
        response = requests.post(
            self.api_url,
            json={"model": self.model_name, "messages": [{"role": "user", "content": prompt}]},
            stream=True  # Enable streaming
        )

        if response.status_code == 200:
            try:
                # Collect the streamed response content
                content = ""
                for line in response.iter_lines():
                    if line:  # Skip empty lines
                        line_data = json.loads(line.decode("utf-8"))
                        message = line_data.get("message", {}).get("content", "")
                        content += message

                return content.strip()  # Return the full content
            except Exception as e:
                raise Exception(f"Failed to parse streaming response: {e}, Raw response: {response.text}")
        else:
            raise Exception(f"Error: {response.status_code}, {response.text}")

    def generate_suggestions(self, section_name, text):
        """
        Generate improvement suggestions for a CV section.
        :param section_name: The name of the CV section.
        :param text: The content of the section.
        :return: A list of suggestions.
        """
        suggestions = []

        if section_name == "EDUCATION":
            # Check if degree details are missing
            if not any(keyword in text.lower() for keyword in ["bachelor", "master", "phd", "degree", "diploma"]):
                suggestions.append("Consider adding your degree details (e.g., Bachelor of Science in Computer Science).")
            # Check if institution details are missing
            if not any(keyword in text.lower() for keyword in ["university", "college", "institute", "school"]):
                suggestions.append("Include the name of the institution where you studied.")

        elif section_name == "PROFESSIONAL EXPERIENCE":
            # Check for measurable achievements
            if not any(keyword in text.lower() for keyword in ["increased", "reduced", "improved", "achieved", "led"]):
                suggestions.append("Add measurable achievements (e.g., 'Increased sales by 20%' or 'Led a team of 5 developers').")
            # Check for action verbs
            if not any(keyword in text.lower() for keyword in ["developed", "managed", "designed", "implemented", "collaborated"]):
                suggestions.append("Use action verbs to describe your responsibilities (e.g., 'Developed a web application').")

        elif section_name == "SKILLS":
            # Suggest adding technical or industry-specific keywords
            if len(text.split()) < 5:  # If the skills section is too short
                suggestions.append("Expand your skills section with relevant technical or industry-specific keywords.")
            suggestions.append("Consider adding skills like 'problem-solving', 'teamwork', or 'communication' if applicable.")

        elif section_name == "CERTIFICATES":
            # Check if certificates are listed
            if len(text.strip()) == 0:
                suggestions.append("Add certifications relevant to your field (e.g., 'AWS Certified Solutions Architect').")

        else:
            # Default suggestion for unrecognized sections
            suggestions.append("Ensure this section is complete and relevant to your CV.")

        return suggestions
    def generate_overall_suggestions(self, improved_cv):
        """
        Generate overall suggestions for the CV based on all sections.
        :param improved_cv: The improved CV data.
        :return: A list of overall suggestions.
        """
        overall_suggestions = []

        # Check if all sections are present
        required_sections = ["EDUCATION", "PROFESSIONAL EXPERIENCE", "CERTIFICATES", "SKILLS"]
        missing_sections = [section for section in required_sections if section not in improved_cv]
        if missing_sections:
            overall_suggestions.append(f"Consider adding the following missing sections: {', '.join(missing_sections)}.")

        # Check for consistency in dates
        for section_name, section_data in improved_cv.items():
            if section_name in ["EDUCATION", "PROFESSIONAL EXPERIENCE"]:
                content = section_data.get("content", "")
                if "Dates" not in content:
                    overall_suggestions.append(f"Ensure that all entries in the {section_name} section include dates.")

        # Add a general suggestion
        overall_suggestions.append("Ensure the CV is tailored to the specific job you are applying for.")

        return overall_suggestions